version: '3.8'

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:latest
    container_name: dbt_hailing
    volumes:
      - ./dbt_project:/usr/app/dbt_project
      - ./credentials.json:/root/.dbt/credentials.json
    working_dir: /usr/app/dbt_project
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt_project
    entrypoint: ["tail", "-f", "/dev/null"]