version: 2

sources:
  - name: source
    schema : rizky_dwh_hailing_source
    tables:
      - name: customer_data
        identifier: production_hailing_source_customer
      - name: driver_data
        identifier: production_hailing_source_driver
      - name: ride_data
        identifier: production_hailing_source_ride
      - name: vehicle_data
        identifier: production_hailing_source_vehicle
    
  - name: staging_tables
    schema : rizky_dwh_hailing_facts
    tables:
      - name: customer_staging
        identifier: production_hailing_staging_customer
      - name: driver_staging
        identifier: production_hailing_staging_driver
      - name: ride_staging
        identifier: production_hailing_staging_ride
      - name: vehicle_staging
        identifier: production_hailing_staging_vehicle
